# Generated by Django 3.2.9 on 2021-11-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procuct',
            new_name='Product',
        ),
    ]
